default: &default
  adapter: 'mysql2'
  encoding: utf8
  database: <%= ENV["DB_NAME"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>
  reconnect: false

test:
  <<: *default
development:
  <<: *default
development_workers:
  <<: *default
